name: Sync Community Files to New Repos

on:
  repository_dispatch:
    types: [new_repo_created]

jobs:
  sync_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout .github repository
        uses: actions/checkout@v4

      - name: Get list of community files
        run: |
          mkdir community-files
          cp CONTRIBUTING.md CODE_OF_CONDUCT.md SECURITY.md LICENSE community-files/ || true

      - name: Clone the new repository
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.event.client_payload.repo_full_name }}.git new-repo
          cd new-repo
          cp -r ../community-files/* .
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add community standard files"
          git push origin main
